name: Django App Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          docker compose up -d --build
          sleep 10

          docker compose run web ./manage.py test main.tests.URLTests.homepage

          docker compose down
